### ISSUE TITLE
Make preview work in production

### ISSUE THREAD

**Issue by Nookbe** [allmarkedup/lookbook#110]
The Preview parsing seems not to work in production.
On heroku during deployment I get the following error:
```
 Don't know how to build task 'lookbook:previews:preparse' (See the list of available tasks with `rake --tasks`) Did you mean?  lookbook:release:bump_version
lookbook:previews:preparse

```

When I try the preparse locally, so when I run:
rake lookbook:previews:preparse
I get the following error:
`rake aborted!
Errno::EROFS: Read-only file system @ dir_s_mkdir - /objects`

Any idea whats behind it?

**Comment by allmarkedup** [comment]
Hi @Nookbe - that is an odd one! It actually looks like two separate problems, one in production and one locally.

On you local machine could you try running `RAILS_ENV=production rake lookbook:previews:preparse` and let me know if that makes any difference?

And could you let me know what OS you are using for your local machine?

**Comment by Nookbe** [comment]
Hi @allmarkedup thank you for the quick and sorry for the late reply.
When I run `RAILS_ENV=production rake lookbook:previews:preparse` i get the same error.
I am running on MacOS locally.

**Comment by ExMember** [comment]
Hi @allmarkedup!

I'm getting the same error locally and on Heroku. (As an added complication, I'm trying to use Lookbook in the dummy app of a Rails engine gem.)

Here's what it looks like locally:

```sh
dummy % RAILS_ENV=production rails lookbook:previews:preparse
rails aborted!
Errno::EROFS: Read-only file system @ dir_s_mkdir - /objects

Tasks: TOP => lookbook:previews:preparse
(See full trace by running task with --trace)
```

And here's what it looks like on Heroku:
```sh
dummy % heroku run rails app:lookbook:previews:preparse
Running rails app:lookbook:previews:preparse on ⬢ uswdscomponents... up, run.6489 (Free)
rails aborted!
Errno::EROFS: Read-only file system @ dir_s_mkdir - /objects

Tasks: TOP => app:lookbook:previews:preparse
(See full trace by running task with --trace)
```

Here's full trace from my local environment:

```sh
dummy % RAILS_ENV=production rails lookbook:previews:preparse --trace
** Invoke lookbook:previews:preparse (first_time)
** Execute lookbook:previews:preparse
rails aborted!
Errno::EROFS: Read-only file system @ dir_s_mkdir - /objects
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/fileutils.rb:211:in `each'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/core_ext/file.rb:59:in `open!'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/serializers/file_system_serializer.rb:41:in `serialize'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/serializers/yardoc_serializer.rb:95:in `serialize'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/registry_store.rb:186:in `save'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/registry.rb:171:in `save'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/lookbook-0.9.1/lib/lookbook/parser.rb:16:in `block in parse'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/serializers/yardoc_serializer.rb:56:in `lock_for_writing'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/registry_store.rb:202:in `lock_for_writing'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/yard-0.9.28/lib/yard/registry.rb:210:in `lock_for_writing'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/lookbook-0.9.1/lib/lookbook/parser.rb:14:in `parse'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/lookbook-0.9.1/lib/tasks/lookbook_tasks.rake:8:in `block (3 levels) in <top (required)>'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3.1/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3.1/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/Users/damienburke/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3.1/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3.1/lib/rails/command.rb:51:in `invoke'
/Users/damienburke/.rvm/gems/ruby-3.1.2/gems/railties-7.0.3.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => lookbook:previews:preparse
```

The local environment is macOS Monterey (12.4) on an M1 Max.

**Comment by allmarkedup** [comment]
@Nookbe @ExMember thanks for the extra info guys, although I've been ill for a few days so haven't had much time to dig into this further just yet.

The stack trace is really useful @ExMember thank you - for some reason it looks like the Yard parser is failing to write to the file system, I could imagine that happening on Heroku but I'm unsure why it should be happening locally.

I'll try and recreate again with a fresh project setup and let you know as soon as I've made any progress. Sorry you are running into these problems!

**Comment by allmarkedup** [comment]
@Nookbe @ExMember good news - I've tracked down the problem and fixed it (I hope!) in v0.9.3 which I've just released. 

Thanks so much for bringing it to my attention and for the detailed information. And if you are still having any problems of course just let me know ☺️

**Comment by Nookbe** [comment]
@allmarkedup sorry for the late response but better late than never: Thanks a lot for fixing this, it works after our upgrade.

**Comment by allmarkedup** [comment]
@Nookbe excellent, thanks for letting me know :-)
